website/project/main/routes.py
from flask import (
    Response,
    render_template,
    Blueprint,
    flash,
    redirect,
    url_for,
    request,
    abort,
)
from flask_login import current_user, login_required
from project.models import Questions, QuestionsAnswered, Mock
from project import db
from project.utils import get_agent, get_action
import random

main = Blueprint("main", __name__)

agent = None
state = None
leverage = 3

@main.route("/")
@main.route("/home")
def home():
    return render_template("main/home.html", title="Home")


@main.route("/about")
def about():
    return render_template("main/about.html", title="About")


@main.route("/trade")
# @login_required
def trade():
    _2022 = [("Mar", 31), ("Apr", 30), ("May", 31), ("Jun", 30), ("Jul", 31), ("Aug", 31), ("Sep", 30), ("Oct", 31), ("Nov", 30), ("Dec", 31)]
    _2023 = [("Jan", 31), ("Feb", 28), ("Mar", 31), ("Apr", 30), ("May", 31), ("Jun", 30), ("Jul", 31), ("Aug", 31), ("Sep", 30), ("Oct", 31), ("Nov", 30), ("Dec", 31)]
    _2024 = [("Jan", 31), ("Feb", 29), ("Mar", 18)]
    calender = [("2022", _2022), ("2023", _2023), ("2024", _2024)]
    total_days = 0
    for year in calender:
        for month in year[1]:
            total_days += month[1]

    new_agent, new_state = get_agent()
    global agent, state
    agent = new_agent
    state = new_state

    # truncate Mock tables's data
    Mock.query.delete()
    db.session.commit()
    
    return render_template("main/topics.html", title="Topics", calender=calender, index=0)

@main.route("/predict/<string:date>")
@login_required
def predict(date):
    global agent, state
    amount = round(0.1 * current_user.balance)
    action, new_state, profit = get_action(agent, state, amount)
    action_type = "buy" if action == 0 else "sell" if action == 1 else "hold"
    profit = round(profit.item()*leverage)
    current_user.balance  = round(current_user.balance + profit)
    data = Mock(Date=date, UID=current_user.id, Amount=amount, Return=profit, Type=action_type)
    db.session.add(data)
    db.session.commit()
    state = new_state
    return {"action": action}

@main.route("/questions/<string:section>/<string:topic>")
@login_required
def questions(section, topic):
    s, t = section.replace("_", " "), topic.replace("_", " ")
    questions = Questions.query.filter_by(Section=s, Topic=t).all()
    answers = QuestionsAnswered.query.filter_by(UID=current_user.id).all()
    answers = {x.QID: (x.Option, x.Status) for x in answers}
    return render_template(
        "main/questions.html",
        title=t,
        questions=questions,
        count=1,
        len=len(questions),
        answers=answers,
    )


@main.route("/save/<string:qid>/<string:status>/<string:selection>")
@login_required
def save(qid, status, selection):
    uid = current_user.id

    data = QuestionsAnswered.query.filter_by(QID=qid, UID=uid).first()
    if data != None:
        data.Status = status
        data.Option = selection
    else:
        data = QuestionsAnswered(
            UID=current_user.id, QID=qid, Status=status, Option=selection
        )

    db.session.add(data)
    db.session.commit()
    return Response(status=204)


@main.route("/mocktest")
@login_required
def mocktest():
    return render_template("main/mocktest.html", title="Mock Test")


@main.route("/mocktest/<string:level>")
@login_required
def mocktest_level(level):
    questions = (
        Questions.query.filter_by(Level=level)  
        .order_by(db.func.random())
        .limit(10)
        .all()
    )
    return render_template(
        "main/mocktest_questions.html",
        title=f"Mock Test - {level}",
        questions=questions,
        count=1,
        len=len(questions),
    )

website/project/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/bootstrap.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">

      <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script defer src="https://code.jquery.com/jquery-3.7.0.js"
            integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
      <script defer src="https://kit.fontawesome.com/ebbc1aa60f.js" crossorigin="anonymous"></script>
      <script defer src="{{url_for('static', filename='js/propper.js')}}"></script>
      <script defer src="{{url_for('static', filename='js/bootstrap.js')}}"></script>
      <script defer src="{{url_for('static', filename='js/app.js')}}"></script>

      <title>{{ title }}</title>

</head>

<body>
      <!-- preloader -->
      <div id="preloader"></div>

      <!-- navbar -->
      <nav>
            <div class="logo"><a href="{{url_for('main.home')}}">
                        <img src="{{url_for('static', filename='img/skillsharp-logo.png')}}" alt="logo">
                        <i>TRADESHARK</i>
                  </a>
            </div>
            <ul class="navigation">
                  <li><a href="{{url_for('main.home')}}">HOME</a></li>
                  <li><a href="{{url_for('main.trade')}}">TRADING</a></li>
                  <!-- <li><a href="{{url_for('main.mocktest')}}">MOCK TEST</a></li> -->
                  <li><a href="{{url_for('main.about')}}">ABOUT US</a></li>
                  {% if current_user.is_authenticated %}
                  {% if current_user.username == "admin" %}
                  <li><a class="pic" href="{{url_for('admin.admin_home')}}">
                              <img src="{{ url_for('static', filename='img/skillsharp-logo.png') }}" alt="dp">
                        </a>
                  </li>
                  {% else %}
                  <li><a class="pic" href="{{url_for('signup_and_login.account')}}">
                              <img src="{{ url_for('static', filename='img/dp/' + current_user.image_file) }}" alt="dp">
                        </a>
                  </li>
                  {% endif %}
                  {% else %}
                  <li><a href="{{url_for('signup_and_login.login')}}">LOGIN</a></li>
                  {% endif %}

            </ul>
            <div class="hamburger">
                  <i class="fa-solid fa-bars on" id="on"></i>
            </div>
            <div class="alert">
                  <ul class="navigation1">
                        <i class='bx bxs-x-circle close'></i>
                        <li><a href="{{url_for('main.home')}}" class="out">HOME</a></li>
                        <li><a href="{{url_for('main.trade')}}" class="out">TRADE</a></li>
                        <!-- <li><a href="{{url_for('main.mocktest')}}" class="out">MOCK TEST</a></li> -->
                        <li><a href="{{url_for('main.about')}}" class="out">ABOUT US</a></li>
                        {% if current_user.is_authenticated %}
                        {% if current_user.username == "admin" %}
                        <li><a href="{{url_for('admin.admin_home')}}">
                                    <img src="{{ url_for('static', filename='img/skillsharp-logo.png') }}"
                                          alt="dp">
                              </a>
                        </li>
                        {% else %}
                        <li><a href="{{url_for('signup_and_login.account')}}">
                                    <img src="{{ url_for('static', filename='img/dp/' + current_user.image_file) }}"
                                          alt="dp">
                              </a>
                        </li>
                        {% endif %}
                        {% else %}
                        <li><a href="{{url_for('signup_and_login.login')}}">LOGIN</a></li>
                        {% endif %}
                  </ul>
                  </i>
            </div>
      </nav>

      <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                  {{ message }}
            </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
      </div>

      {% block content %}{% endblock %}

      <!-- footer -->
      <footer>
            <div class="footer-bottom">
                  &copy; TRADESHARK | Designed by <a href="{{url_for('main.about')}}">Team TradeShark</a>
            </div>
      </footer>
</body>

</html>

<script>
      var loader = document.querySelector("#preloader");
      window.addEventListener("load", function () {
            loader.style.display = "none";
      })
</script>