website/project/signup_and_login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from project.models import User
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user



class RegistrationForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError("The username is taken, try another one")
        
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError("The email is taken, try another one")
        
    def validate_password(self, password):
        if len(password.data) < 6:
            raise ValidationError("Password should be atlest 6 character")



class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png', "jpeg"])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')
            
            
            
class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('There is no account with that email. You must register first.')
    


class ResetPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

    def validate_password(self, password):
        if len(password.data) < 6:
            raise ValidationError("Password should be atlest 6 character")

website/project/signup_and_login/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort, Response
from project import db, bcrypt
from project.signup_and_login.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
)
from project.models import User
from flask_login import login_user, current_user, logout_user, login_required
from project.signup_and_login.forms import RequestResetForm, ResetPasswordForm
from project.signup_and_login.utils import save_picture, send_reset_email
from project.models import Mock

signup_and_login = Blueprint("signup_and_login", __name__)


@signup_and_login.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = RegistrationForm()
    if request.method == "GET":
        return render_template(
            "signup_and_login/register.html", title="Register", form=form
        )
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in", "success")
        return redirect(url_for("signup_and_login.login"))
    
    flash(
        "Registration Unsuccessful. Please check your details and try again", "danger"
    )

    return render_template(
        "signup_and_login/register.html", title="Register", form=form
    )


@signup_and_login.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    
    if request.method == "GET":
        return render_template("signup_and_login/login.html", title="Login", form=form)
        
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            flash("Login Successful ", "success")
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            if user == None:
                flash("Login Unsuccessful. User does not exist", "danger")
            else:
                flash("Login Unsuccessful. Wrong password", "danger")
                
    return render_template("signup_and_login/login.html", title="Login", form=form)


@signup_and_login.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out", "success")
    return redirect(url_for("main.home"))


@signup_and_login.route("/account", methods=["GET", "POST"])
@login_required
def account():
    if current_user.username == "admin":
        abort(403)
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("signup_and_login.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="img/dp/" + current_user.image_file)
    mocks = Mock.query.filter_by(UID=current_user.id).all()
    return render_template(
        "signup_and_login/account.html",
        title="Account",
        image_file=image_file,
        form=form,
        mocks=mocks,
        balance=current_user.balance,
    )


@signup_and_login.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    form = RequestResetForm()
    
    if request.method == "GET":
        return render_template("signup_and_login/reset_request.html", title="Reset Password", form=form)
    
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user == None:
            flash("Email does not exist", "danger")
            return redirect(url_for("signup_and_login.reset_request"))
        send_reset_email(user)
        flash("An email has been sent with a link to reset your password.","info",)
        return redirect(url_for("signup_and_login.login"))
    
    return render_template("signup_and_login/reset_request.html", title="Reset Password", form=form)


@signup_and_login.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    
    user = User.query.filter(User.password.like(f"{token}%")).first()
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("signup_and_login.reset_request"))
    
    form = ResetPasswordForm()
    if request.method == "GET":
        return render_template(
            "signup_and_login/reset_token.html", title="Reset Password", form=form
        )
        
    if form.validate_on_submit():
        new_hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = new_hashed_password
        db.session.commit()
        flash("Your password has been updated! You are now able to log in", "success")
        return redirect(url_for("signup_and_login.login"))
    
    return render_template(
        "signup_and_login/reset_token.html", title="Reset Password", form=form
    )

@signup_and_login.route("/account/save_amount/<int:amount>")
@login_required
def save_amount(amount):
    current_user.balance = amount
    db.session.commit()
    return Response(status=204)

website/project/templates/signup_and_login/account.html
{% extends "layout.html" %}
{% block content %}

<div class="balance-container text-center">
    <h2>BALANCE</h2>
    <div class="balance-amount-container">
        <button class="btn btn-m btn-danger" onclick="decreaseBalance()">-</button>
        <p class="balance-amount">{{ balance }}</p>
        <button class="btn btn-m btn-success" onclick="increaseBalance()">+</button>
    </div>
</div>
<style>
    .balance-container {
        margin-top: 20px;
    }

    .balance-amount {
        font-size: 50px;
        font-weight: bold;
    }

    .balance-container button {
        margin: 10px;
    }

    .mock-history-container {
        margin-top: 20px;
    }

    .balance-amount-container {
        display: flex;
        justify-content: center;
        align-items: center;
    }
</style>


<div class="account-section">
    <div class="media">
        <img class="rounded-circle account-img"
             src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
        <button class="btn btn-outline-danger"><a href="{{url_for('signup_and_login.logout')}}">logout</a></button>
    </div>
    <form method="POST"
          action=""
          enctype="multipart/form-data"
          class="account-form">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>



<div class="mock-history-container">
    <h2>Trade HISTORY</h2>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Amount</th>
            <th scope="col">Type</th>
            <th scope="col">Return</th>
        </tr>
        </thead>
        <tbody>
        {% for trade in mocks %}
        <tr>
            <td>{{ trade.Date }}</td>
            <td>{{ trade.Amount }}</td>
            <td>{{ trade.Type }}</td>
            <td>{{ trade.Return }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

website/project/templates/signup_and_login/login.html
{% extends "layout.html" %}
{% block content %}


<div>
    <div class="content-section login-container">
        <form method="POST" action="" class="login-form">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
                <div class="d-flex justify-content-between">
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                    <small class="text-muted">
                        <a href="{{ url_for('signup_and_login.reset_request') }}"><span class="link">Forgot
                                Password?</span></a>
                    </small>
    
                </div>
            </fieldset>
            <div class="border-top">
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{{ url_for('signup_and_login.register') }}"> <span class="link"> Sign
                            Up Now</span></a>
                </small>
            </div>
        </form>
    </div>
</div>


{% endblock %}

website/project/templates/signup_and_login/register.html
{% extends "layout.html" %}
{% block content %}


<div class="content-section register-container">
    <form method="POST" action="/register" class="register-form">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <div class="border-top">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{{ url_for('signup_and_login.login') }}"><span class="link">Sign In</span></a>
            </small>
        </div>
    </form>
</div>


{% endblock %}

website/project/templates/signup_and_login/reset_request.html
{% extends "layout.html" %}
{% block content %}


    <div class="content-section register-container">
        <form method="POST" action="" class="register-form">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-3">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

    
{% endblock content %}

website/project/templates/signup_and_login/reset_token.html
{% extends "layout.html" %}
{% block content %}


    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

    
{% endblock content %}